// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"TTS","status":true,"description":"Text To Speech plugin. work only native browser.","parameters":{"Run TTS":"T","Stop TTS":"TT","noInterrupt":"false"}}
];
